### ISSUE TITLE
this extend was not function after some updates on chatGPT

### ISSUE THREAD

**Issue by Taka22222** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#48]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
this extend was not function after some updates on chatGPT.
function of beginning new line is ok but ctrl + send is not functional.
I use your extend and super power chat GPT like below at same time.
https://chromewebstore.google.com/detail/superpower-chatgpt/amhmeenmapldpjdedekalnfifgnpfnkc
before some update on chatGPT itself ctrl + send was functional.

### Steps to reproduce
1. ..active superpower chatGPT
2. ..then use chatGPT ctrl + sender 

**Expected behavior** [What you expected to happen.]
ctrl + send is not functional during use superpower chatGPT.
**Actual behavior** [What actually happened.]
ctrl + send is functional during use superpower chatGPT.
**Screenshots**         
n.a.

### Additional context
Windows10 and google chrome.

**Comment by masachika-kamada** [comment]
@Taka22222 
Thank you for reporting this issue and for providing such a detailed description. 

After reviewing your report, it seems that the issue is not a bug with the "ChatGPT Ctrl+Enter Sender" extension, but rather a result of the changes made by the "Superpower ChatGPT" extension. It appears that the "Superpower ChatGPT" extension modifies the textarea element, which could be the reason why the expected behavior is not occurring. 

As the developer of "ChatGPT Ctrl+Enter Sender", I can confirm that the extension should function as intended when used on its own. However, I am not affiliated with the "Superpower ChatGPT" extension, and therefore cannot comment on their development choices or potential issues with their code. 

Given this information, it seems that the issue is not a bug with your extension but an incompatibility between the two extensions. This is likely due to the modifications made by "Superpower ChatGPT" to the textarea element, which may interfere with the functionality of other extensions. 

To resolve this issue, please try using only one of the extensions at a time. You can do this by disabling one of the extensions in your browser settings. This should allow you to use the "ChatGPT Ctrl+Enter Sender" extension as intended without any interference from the other extension. 

Thank you again for bringing this to our attention, and we apologize for any inconvenience caused.

**Comment by Taka22222** [comment]
Kamada-san
Thank you.
However this ploblem should be solved by cooparation your company and veder of Superpower Chat GPT.
Almost user desire use both extention at same time.
Could you contact veder of Superpower Chat GPT? or if you give more information,I
 can try contact theire.
Best reguards.

**Comment by masachika-kamada** [comment]
@Taka22222 san
Thank you for your report and for bringing this issue to our attention. I apologize for the delayed response.


Regarding the compatibility with the "Superpower ChatGPT" extension, I have to inform you that we currently cannot provide direct support for other extensions. Ensuring compatibility across all possible combinations is a challenging task, and it might inadvertently affect other users' experiences.


Please understand that "ChatGPT Ctrl+Enter Sender" is a personal project that I develop and maintain in my free time. It is not feasible for me to test all possible user environments and extension combinations. Compatibility issues can be intricate, and we must consider the potential impact on the broader user base.


At this time, I will refrain from proactively reaching out to the developers of "Superpower ChatGPT." However, I acknowledge that many users would benefit from seamless integration between the two extensions. Should the developers of "Superpower ChatGPT" express interest in discussing this matter, I am open to collaborating within my capacity. Open-source communities thrive on such cooperation and dialogue.


If you wish to take the initiative, you may consider reaching out to the developers of "Superpower ChatGPT" directly. Their contact information might be available, enabling a direct conversation about this issue.


Thank you for using our extension. We appreciate your feedback and are always open to hearing from our users.

**Comment by Taka22222** [comment]
Kameda-san
OK I understand your situation.
However please remember this inquery from me.
I hope your good future and your job is so great!!
