### ISSUE TITLE
Enter Key Sends Message Instead of Creating New Line After September 12 (JST)

### ISSUE THREAD

**Issue by sahksas** [masachika-kamada/ChatGPT-Ctrl-Enter-Sender#54]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

Since September 12 (JST), the expected behavior has stopped working. When pressing the Enter key, the chat is sent instead of creating a new line.

### Steps to reproduce
1. Access https://chatgpt.com/
2. Enter text in the text field
3. Press the Enter key

#### Expected behavior

The Enter key should create a new line in the text field.

#### Actual behavior

The text is sent instead of creating a new line.

### Additional context

- Windows 11
- Google Chrome 128.0.6613.121

**Comment by arakisin** [comment]
I am experiencing the same issue.  
OS: Windows 11  
Browser: Google Chrome 128.0.6613.121

**Comment by sahksas** [comment]
- The issue persists even when all other extensions are turned off.
- Pressing Shift+Enter inputs a space instead of creating a new line.

**Comment by chendonming** [comment]
I am experiencing the same issue in 2024/9/12

OS: Windows 11
Browser: Google Chrome 128.0.6613.121

Thank you for what you've done.

**Comment by natsuki-de-yak** [comment]
I am experiencing the same issue since 2024/9/11.
I also changed my browser to Mozilla Firefox and the same issue occurred.

OS: Windows 10
Browser: Google Chrome 128.0.6613.138, Mozilla Firefox 130.0

**Comment by sahksas** [comment]
I'm not sure when it changed, but it seems that the ChatGPT text area tag is actually a div rather than a textarea. This appears to be one of the causes of the issue, so I'll continue investigating.

https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/blob/e6959685c43de4e2ba8dfcef394d8956c471803c/script.js#L2-L4

**Comment by goro-56-who** [comment]
Please simply add support for this site:
https://chatgpt.com/

Here is the reason:

The domain this addon currently supports is:
https://chat.openai.com/

Before, I could use ChatGPT at this URL:
https://chat.openai.com/chat

Now, this URL redirects to:
https://chatgpt.com/

I would be really happy if you could add support for it.

**Comment by sahksas** [comment]
to: maintainer

I have forked the repository and created a PR to resolve the issue.

https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/pull/55

**Comment by TaoTadarjo** [comment]
Edgeだと「shift+enter」で改行できます。

**Comment by sahksas** [comment]
@TaoTadarjo 
こちらの環境ではEdgeでも不具合は再現しています。あなたのEdgeにこの拡張機能は入っていますか？
改行が必要であれば、一時的にこの拡張機能をオフにすることをおすすめします。

---

The issue is also reproducible in Edge in my environment. Do you have this extension installed on your Edge? If line breaks are necessary, I recommend temporarily disabling this extension.

**Comment by sahksas** [comment]
@goro-56-who 

I believe this has been addressed.

https://github.com/masachika-kamada/ChatGPT-Ctrl-Enter-Sender/blob/e6959685c43de4e2ba8dfcef394d8956c471803c/manifest.json#L17-L27

**Comment by goro-56-who** [comment]
@sahksas
申し訳ありません。
トップページの紹介文を見て判断してしまいました。

また、「May be fixed by #55」を見落としていました。
重ねてお詫び申し上げます。

#55 のソースを拡張機能として使用したところ、私の以下の環境では無事に動作しました。

Windows 11
Google Chrome 128.0.6613.138


以下は、他の方のための情報です。

Google Chrome の拡張機能管理ページにある右上の「デベロッパー モード」を有効にしてください。

すると、メニューが上部に表示されます。

「パッケージ化されていない拡張機能を読み込む」から #55 のソース（以下のURL）を読み込んでください。
https://github.com/sahksas/ChatGPT-Ctrl-Enter-Sender/tree/bugfix-linebreak

これを使用すれば、無事に動作しました。

=================================

Sorry.

I judged based on the top page introduction.

And I missed the issue information that said "May be fixed by #55."

I'm very sorry.

When I used the #55 source as an add-on, I could use "ChatGPT-Ctrl-Enter-Sender" successfully.

My environment is below:

Windows 11
Google Chrome 128.0.6613.138


For others who may be confused:

Try using the source from the following URL:
https://github.com/sahksas/ChatGPT-Ctrl-Enter-Sender/tree/bugfix-linebreak

Then, install the add-on from this source, and you will be able to use "ChatGPT-Ctrl-Enter-Sender."
